//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTFYP
{


    public partial class AddScholarship
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtRequirement;
        protected global::System.Web.UI.WebControls.TextBox txtTerms;
        protected global::System.Web.UI.WebControls.TextBox txtCourses;
        protected global::System.Web.UI.WebControls.TextBox txtLink;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
